### PR TITLE
Update plugin.yml

### PR DESCRIPTION
**Pull request by MCNationPE**

### CODE REVIEW

**Comment by Driesboy** [comment]
does it works on ALPHA6?

**Comment by Driesboy** [comment]
did you test?

**Comment by Driesboy** [comment]
?

**Comment by MCNationPE** [comment]
[07:53:40] [Server thread/INFO]: Loading source plugin EggWars v1
[07:53:40] [Server thread/INFO]: Loading source plugin TimeCommander v2.1
[07:53:40] [Server thread/INFO]: Preparing level "world"

**Comment by MCNationPE** [comment]
image

**Pull request merged**
