### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by MCPEATECH**
`# Plugin coding: Enes5519 & Driesboy
# Only works on PMMP and derived softwares such as Bluelight 

### API3 version -> https://github.com/NL-4-DEVS/Eggwars/tree/API3

[Poggit-CI](https://poggit.pmmp.io/ci/GameCraftPE/Eggwars/Eggwars)

### Installation:
####Hello, the installation of the plugin Is simple:
####Step 1: Download the most recent release of the plugin from github or poggit.pmmp.io.
####Step 2: Drop the .phar into your servers plugins folder and (re)start your server.
####Step 3: Make sure the plugin loads on the console, and your good to go :)

### CODE REVIEW

**Comment by Driesboy** [comment]
exact copy if my plugin for @gamecraftpe

**Comment by MCPEATECH** [comment]
no it was the updated readme....

**Comment by Driesboy** [comment]
facepalm

**Comment by MCPEATECH** [comment]
so was that my bad or yours?

**Comment by Driesboy** [comment]
you just merged the @gamecraftpe branch into this one
without any change for the readme

**Comment by MCPEATECH** [comment]
The read me was completely rewritten :P?????!?!?!?

**Pull request closed without merging**
